# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
  - main: ./cmd/ipsw
    binary: ipsw
    env:
      - CGO_ENABLED=1
      - CC=gcc
    hooks:
      pre: go generate ./...
    goos:
      - windows
      - darwin
      # - linux
    goarch:
      - amd64
    ldflags: -s -w -X github.com/blacktop/ipsw/cmd/ipsw/cmd.AppVersion={{.Version}} -X github.com/blacktop/ipsw/cmd/ipsw/cmd.AppBuildTime={{.Date}}

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      amd64: amd64
      darwin: macOS
      linux: linux
      windows: win

brews:
  - github:
      owner: blacktop
      name: homebrew-tap
    folder: Formula
    homepage: "https://github.com/blacktop/ipsw"
    description: "Download and parse ipsw(s)"
    test: |
      system "#{bin}/ipsw --version"

checksum:
  name_template: "checksums.txt"

signs:
  - artifacts: checksum

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^bumping"
      - "update README"
      - "Update README.md"
      - "fixes"
