# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - main: ./cmd/ipsw
    id: darwin
    binary: ipsw
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags: -s -w -X github.com/blacktop/ipsw/cmd/ipsw/cmd.AppVersion={{.Version}} -X github.com/blacktop/ipsw/cmd/ipsw/cmd.AppBuildTime={{.Date}}
  - main: ./cmd/ipsw
    id: "others"
    binary: ipsw
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags: -s -w -X github.com/blacktop/ipsw/cmd/ipsw/cmd.AppVersion={{.Version}} -X github.com/blacktop/ipsw/cmd/ipsw/cmd.AppBuildTime={{.Date}}
universal_binaries:
  - id: darwin
    replace: false
archives:
  - replacements:
      darwin: macOS
      amd64: x86_64
      all: universal
    format_overrides:
      - goos: windows
        format: zip
brews:
  - tap:
      owner: blacktop
      name: homebrew-tap
    folder: Formula
    homepage: "https://github.com/blacktop/ipsw"
    description: "Download and parse ipsw(s)"
    dependencies:
      - name: bat
        type: optional
    install: |
      bin.install "ipsw"
    test: |
      system "#{bin}/ipsw --version"
      bash_completion.install "hack/completions/_bash" => "ipsw"
      zsh_completion.install "hack/completions/_zsh" => "_ipsw"
      fish_completion.install "hack/completions/_fish" => "ipsw.fish"

checksum:
  name_template: "checksums.txt"
signs:
  - artifacts: checksum
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^bumping"
      - "^Update"
      - "reorg"
      - "updates"
      - Merge pull request
      - Merge branch
