# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
  - main: ./cmd/ipsw
    binary: ipsw
    env:
      - CGO_ENABLED=1
      # - CC=gcc
      - CGO_CFLAGS=-I/usr/local/include
      - CGO_LDFLAGS=-L/usr/local/lib
    hooks:
      pre: go generate ./...
    goos:
      # - windows
      - darwin
      # - linux
    goarch:
      - amd64
    ldflags: -s -w -X github.com/blacktop/ipsw/cmd/ipsw/cmd.AppVersion={{.Version}} -X github.com/blacktop/ipsw/cmd/ipsw/cmd.AppBuildTime={{.Date}}

  - id: ipsw_extended_windows
    main: ./cmd/ipsw
    binary: ipsw
    ldflags:
      - -s -w -X github.com/blacktop/ipsw/cmd/ipsw/cmd.AppVersion={{.Version}} -X github.com/blacktop/ipsw/cmd/ipsw/cmd.AppBuildTime={{.Date}}
      # - "-extldflags '-static'"
    env:
      - CGO_ENABLED=0
    #   - CC=x86_64-w64-mingw32-gcc
    #   - CXX=x86_64-w64-mingw32-g++
    #   - LDFLAGS="-L/usr/local/Cellar/lzfse/1.0/lib -llzfse"
    # flags:
    #   - -tags
    #   - extended
    goos:
      - windows
    goarch:
      - amd64

  # - id: ipsw_extended_darwin
  #   env:
  #     - CGO_ENABLED=0
  #   main: ./cmd/ipsw
  #   binary: ipsw
  #   ldflags: -s -w -X github.com/blacktop/ipsw/cmd/ipsw/cmd.AppVersion={{.Version}} -X github.com/blacktop/ipsw/cmd/ipsw/cmd.AppBuildTime={{.Date}}
  #   goos:
  #     - darwin
  #   goarch:
  #     - amd64
  # - id: ipsw_extended_linux
  #   main: ./cmd/ipsw
  #   binary: ipsw
  #   ldflags: -s -w -X github.com/blacktop/ipsw/cmd/ipsw/cmd.AppVersion={{.Version}} -X github.com/blacktop/ipsw/cmd/ipsw/cmd.AppBuildTime={{.Date}}
  #   env:
  #     - CGO_ENABLED=1
  #   flags:
  #     - -tags
  #     - extended
  #   goos:
  #     - linux
  #   goarch:
  #     - amd64

archives:
  - id: darwin
    builds:
      - ipsw
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}_extras"
    format: tar.gz
    replacements:
      darwin: macOS
  - id: windows
    builds:
      - ipsw_extended_windows
    format: zip
    replacements:
      windows: win
  - id: extras
    builds:
      - ipsw_extended_darwin
    format: tar.gz
    replacements:
      darwin: macOS

brews:
  - ids:
      - darwin
    tap:
      owner: blacktop
      name: homebrew-tap
    folder: Formula
    homepage: "https://github.com/blacktop/ipsw"
    description: "Download and parse ipsw(s)"
    dependencies:
      - lzfse
      - bat
    install: |
      bin.install "ipsw"
    test: |
      system "#{bin}/ipsw --version"

checksum:
  name_template: "checksums.txt"

signs:
  - artifacts: checksum

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^bumping"
      - "^Update"
      - "reorg"
      - "updates"
      - Merge pull request
      - Merge branch
