# appveyor.yml
build: off

clone_folder: c:\gopath\src\github.com\blacktop\ipsw

shallow_clone: true

environment:
  GOPATH: c:\gopath

stack: go 1.10

# before_test:
#   - go vet ./...

test_script:
  - CGO_ENABLED=0 go build github.com/blacktop/ipsw/cmd/ipsw
  - ipsw.exe download --device iPhone11,2 --build 16B92 kernel
