name: Go
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Build Dependencies (Linux)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update && sudo apt-get install -y cmake libtool libc6-dev
          cd /tmp
          git clone https://github.com/lzfse/lzfse.git
          cd lzfse
          mkdir build
          cd build
          cmake ..
          sudo make install
      - name: Build Dependencies (macOS)
        if: matrix.platform == 'macos-latest'
        run: |
          brew install lzfse
      # - name: Build Dependencies (Windows)
      #   if: matrix.platform == 'windows-latest'
      #   run: |
      #     git clone https://github.com/lzfse/lzfse.git
      #     cd lzfse
      #     mkdir build
      #     cd build
      #     cmake -G "Visual Studio 16 2019" ..
      #     cmake --build . --config Debug
      #     cd Debug
      #     dlltool --def D:\a\ipsw\ipsw\hack\windows\lzfse.def --dllname lzfse.dll --output-lib lzfse.a

      - name: Get dependencies
        run: |
          go mod download

      - name: Build (Linux)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
          CGO_ENABLED=1 go build -o build/dist/ipsw -ldflags "-s -w -X github.com/blacktop/ipsw/cmd/ipsw/cmd.AppVersion="v1.0.0" -X github.com/blacktop/ipsw/cmd/ipsw/cmd.AppBuildTime==$(date -u +%Y%m%d)" ./cmd/ipsw
      - name: Build (macOS)
        if: matrix.platform == 'macos-latest'
        run: sudo CGO_ENABLED=1 go build -o build/dist/ipsw -ldflags "-s -w -X github.com/blacktop/ipsw/cmd/ipsw/cmd.AppVersion="v1.0.0" -X github.com/blacktop/ipsw/cmd/ipsw/cmd.AppBuildTime==$(date -u +%Y%m%d)" ./cmd/ipsw
      - name: Build (Windows)
        if: matrix.platform == 'windows-latest'
        env:
          CGO_LDFLAGS: -LD:\a\ipsw\ipsw\lzfse\build\Debug
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          go build -o build/dist/ipsw.exe -ldflags "-linkmode external -extldflags -static" ./cmd/ipsw
          dir build/dist
          dir

      # - name: Run Help
      #   if: matrix.platform == 'ubuntu-latest' || matrix.platform == 'macos-latest'
      #   run: LD_LIBRARY_PATH=/usr/local/lib build/dist/ipsw --help
      # - name: Run Help (Windows)
      #   if: matrix.platform == 'windows-latest'
      #   run: D:\a\ipsw\ipsw\build\dist\ipsw.exe --help

      - name: Run Device List
        if: matrix.platform == 'ubuntu-latest' || matrix.platform == 'macos-latest'
        run: LD_LIBRARY_PATH=/usr/local/lib build/dist/ipsw device-list
      - name: Run Device List (Windows)
        if: matrix.platform == 'windows-latest'
        run: D:\a\ipsw\ipsw\build\dist\ipsw.exe device-list

      - id: get-latest
        if: matrix.platform == 'ubuntu-latest' || matrix.platform == 'macos-latest'
        run: |
          echo ::set-output name=version::$(LD_LIBRARY_PATH=/usr/local/lib build/dist/ipsw download latest --info)

      - name: Run Extract Remote Kernelcache
        if: matrix.platform == 'ubuntu-latest'
        run: |
          LD_LIBRARY_PATH=/usr/local/lib build/dist/ipsw -V download kernel -v 14.6 -d iPhone12,1
          LD_LIBRARY_PATH=/usr/local/lib build/dist/ipsw -V macho */kernelcache*

      - name: Run Extract Remote Kernelcache (Windows)
        if: matrix.platform == 'windows-latest'
        run: |
          D:\a\ipsw\ipsw\build\dist\ipsw.exe -V download kernel -v 14.6 -d iPhone12,1
          dir

      - name: Run Extract ALL Remote Kernelcaches
        if: matrix.platform == 'macos-latest'
        run: |
          LD_LIBRARY_PATH=/usr/local/lib build/dist/ipsw download kernel -v 14.6 -d iPhone12,1
          LD_LIBRARY_PATH=/usr/local/lib build/dist/ipsw -V macho */kernelcache*
      #
      # DOWNLOAD CMD (macOS)
      #
      - name: Run download latest
        if: matrix.platform == 'macos-latest'
        run: |
          export PATH=$PWD/build/dist:$PATH
          cd /tmp && LD_LIBRARY_PATH=/usr/local/lib ipsw download latest --device iPhone12,1 --yes
      #
      # EXTRACT CMD (macOS)
      #
      - name: Run extract - (kernel, dsc and dtree)
        if: matrix.platform == 'macos-latest'
        run: |
          export PATH=$PWD/build/dist:$PATH
          cd /tmp && LD_LIBRARY_PATH=/usr/local/lib ipsw extract --kernel --dyld --dtree *.ipsw
      #
      # KERNEL CMD (macOS)
      #
      - name: Run kernel kexts
        if: matrix.platform == 'macos-latest'
        run: |
          LD_LIBRARY_PATH=/usr/local/lib build/dist/ipsw kernel kexts /tmp/*iPhone11,8_iPhone12,1/kernelcache.release.iPhone11,8
      - name: Run kernel sbopts
        if: matrix.platform == 'macos-latest'
        run: |
          LD_LIBRARY_PATH=/usr/local/lib build/dist/ipsw kernel sbopts /tmp/*iPhone11,8_iPhone12,1/kernelcache.release.iPhone11,8
      #
      # DYLD CMD (macOS)
      #
      - name: Run dyld info
        if: matrix.platform == 'macos-latest'
        run: |
          LD_LIBRARY_PATH=/usr/local/lib build/dist/ipsw dyld info /tmp/*iPhone11,8_iPhone12,1/dyld_shared_cache_arm64e --dylibs --sig -V

      - name: Run dyldsymaddr (img)
        if: matrix.platform == 'macos-latest'
        run: |
          LD_LIBRARY_PATH=/usr/local/lib build/dist/ipsw dyld symaddr /tmp/*iPhone11,8_iPhone12,1/dyld_shared_cache_arm64e --image libsystem_c.dylib
      - name: Run dyld symaddr (sym)
        if: matrix.platform == 'macos-latest'
        run: |
          LD_LIBRARY_PATH=/usr/local/lib build/dist/ipsw dyld symaddr /tmp/*iPhone11,8_iPhone12,1/dyld_shared_cache_arm64e _memcpy
      - name: Run dyld symaddr (img+sym)
        if: matrix.platform == 'macos-latest'
        run: |
          LD_LIBRARY_PATH=/usr/local/lib build/dist/ipsw dyld symaddr /tmp/*iPhone11,8_iPhone12,1/dyld_shared_cache_arm64e --image libsystem_c.dylib _memcpy
      - name: Run dyld symaddr (ALL)
        if: matrix.platform == 'macos-latest'
        run: |
          LD_LIBRARY_PATH=/usr/local/lib build/dist/ipsw dyld symaddr /tmp/*iPhone11,8_iPhone12,1/dyld_shared_cache_arm64e | grep _memcpy

      - name: Run dyld macho
        if: matrix.platform == 'macos-latest'
        run: |
          LD_LIBRARY_PATH=/usr/local/lib build/dist/ipsw dyld macho /tmp/*iPhone11,8_iPhone12,1/dyld_shared_cache_arm64e JavaScriptCore --loads --objc --strings --symbols --starts -V

      - name: Run dyld webkit
        if: matrix.platform == 'macos-latest'
        run: |
          LD_LIBRARY_PATH=/usr/local/lib build/dist/ipsw dyld webkit /tmp/*iPhone11,8_iPhone12,1/dyld_shared_cache_arm64e --rev

      - name: Run dyld slide
        if: matrix.platform == 'macos-latest'
        run: |
          LD_LIBRARY_PATH=/usr/local/lib build/dist/ipsw dyld slide /tmp/*iPhone11,8_iPhone12,1/dyld_shared_cache_arm64e --auth

      - name: Run dyld patches
        if: matrix.platform == 'macos-latest'
        run: |
          LD_LIBRARY_PATH=/usr/local/lib build/dist/ipsw dyld patches /tmp/*iPhone11,8_iPhone12,1/dyld_shared_cache_arm64e

      - name: Run dyld imports
        if: matrix.platform == 'macos-latest'
        run: |
          LD_LIBRARY_PATH=/usr/local/lib build/dist/ipsw dyld imports /tmp/*iPhone11,8_iPhone12,1/dyld_shared_cache_arm64e JavaScriptCore

      - name: Run dyld disass
        if: matrix.platform == 'macos-latest'
        run: |
          LD_LIBRARY_PATH=/usr/local/lib build/dist/ipsw dyld disass /tmp/*iPhone11,8_iPhone12,1/dyld_shared_cache_arm64e --demangle --symbol _NSLog

      - name: Run dyld objc sel --image
        if: matrix.platform == 'macos-latest'
        run: |
          LD_LIBRARY_PATH=/usr/local/lib build/dist/ipsw dyld objc sel /tmp/*iPhone11,8_iPhone12,1/dyld_shared_cache_arm64e --image JavaScriptCore
      - name: Run dyld objc --class
        if: matrix.platform == 'macos-latest'
        run: |
          LD_LIBRARY_PATH=/usr/local/lib build/dist/ipsw dyld objc --class /tmp/*iPhone11,8_iPhone12,1/dyld_shared_cache_arm64e
      - name: Run dyld objc --imp-cache
        if: matrix.platform == 'macos-latest'
        run: |
          LD_LIBRARY_PATH=/usr/local/lib build/dist/ipsw dyld objc --imp-cache /tmp/*iPhone11,8_iPhone12,1/dyld_shared_cache_arm64e
      - name: Run dyld objc --proto
        if: matrix.platform == 'macos-latest'
        run: |
          LD_LIBRARY_PATH=/usr/local/lib build/dist/ipsw dyld objc --proto /tmp/*iPhone11,8_iPhone12,1/dyld_shared_cache_arm64e

      - name: Run dyld split
        if: matrix.platform == 'macos-latest'
        run: |
          export PATH=$PWD/build/dist:$PATH
          cd /tmp && LD_LIBRARY_PATH=/usr/local/lib ipsw dyld split /tmp/*iPhone11,8_iPhone12,1/dyld_shared_cache_arm64e /tmp
      #
      # MACHO CMD (macOS)
      #
      - name: Run macho
        if: matrix.platform == 'macos-latest'
        run: |
          export PATH=$PWD/build/dist:$PATH
          cd /tmp && LD_LIBRARY_PATH=/usr/local/lib ipsw macho /tmp/System/Library/Frameworks/JavaScriptCore.framework/JavaScriptCore --ent --header --loads --starts --strings --symbols
      #
      # ENT CMD (macOS)
      #
      - name: Run ents
        if: matrix.platform == 'macos-latest'
        run: |
          LD_LIBRARY_PATH=/usr/local/lib build/dist/ipsw ent /tmp/*.ipsw --ent platform-application
      #
      # INFO CMD (macOS)
      #
      - name: Run info
        if: matrix.platform == 'macos-latest'
        run: |
          LD_LIBRARY_PATH=/usr/local/lib build/dist/ipsw info /tmp/*.ipsw

      # - name: Run ipsw update
      #   if: matrix.platform == 'macos-latest'
      #   run: |
      #     build/dist/ipsw update --platform windows_x86_64 -V
      #     build/dist/ipsw update --detect

      - uses: actions/upload-artifact@v2
        with:
          name: Releases
          path: build/dist/
