name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Install lzfse
        run: |
          sudo apt-get update && sudo apt-get install -y cmake
          cd /tmp
          git clone https://github.com/lzfse/lzfse.git
          cd lzfse
          mkdir build
          cd build
          cmake ..
          sudo make install

      - name: Get dependencies
        run: |
          go mod download

      - name: Run Help
        run: CGO_ENABLED=1 go run cmd/ipsw/main.go --help

      - name: Run Device List
        run: CGO_ENABLED=1 go run cmd/ipsw/main.go device list

      - name: Run Extract Remote Kernelcache
        run: CGO_ENABLED=1 go run cmd/ipsw/main.go -V extract -r -k https://updates.cdn-apple.com/2019FallSeed/fullrestores/061-28687/1A71B3E2-EA30-11E9-B7D3-A61B17E817B4/iPhone12,3,iPhone12,5_13.2_17B5068e_Restore.ipsw
